local luassert = require("luassert")
local event_bus_mod = require("src.tactics.systems.event_bus")
local stats_service_mod = require("src.tactics.campaign.statistics.stats_service")

local function new_service()
    return stats_service_mod.new(event_bus_mod.new())
end

describe("tactics.story.statistics.stats_service", function()
    describe("record_recruitment", function()
        it("records the chapter for a recruited unit", function()
            local svc = new_service()
            svc:record_recruitment(42, 3)
            luassert.are_equal(3, svc.story_results.chapter_recruited[42])
        end)

        it("records multiple units independently", function()
            local svc = new_service()
            svc:record_recruitment(1, 1)
            svc:record_recruitment(2, 2)
            luassert.are_equal(1, svc.story_results.chapter_recruited[1])
            luassert.are_equal(2, svc.story_results.chapter_recruited[2])
        end)

        it("overwrites a previous recruitment entry for the same unit", function()
            local svc = new_service()
            svc:record_recruitment(5, 1)
            svc:record_recruitment(5, 2)
            luassert.are_equal(2, svc.story_results.chapter_recruited[5])
        end)

        it("chapter_recruited starts empty", function()
            local svc = new_service()
            luassert.are_same({}, svc.story_results.chapter_recruited)
        end)
    end)

    describe("get_as_map", function()
        it("returns empty table when no chapters recorded", function()
            local svc = new_service()
            luassert.are_same({}, svc:get_as_map())
        end)

        it("serializes a single chapter", function()
            local svc = new_service()
            svc:begin_chapter(1, "battle_1")
            svc:record_battle_end({ chapter = 1, turn_number = 5, result = "VICTORY" })
            local map = svc:get_as_map()
            luassert.are_equal("0", map["stats.1.units_lost"])
            luassert.are_equal("5", map["stats.1.turns_taken"])
            luassert.are_equal("0", map["stats.current.units_lost"])
            luassert.are_equal("5", map["stats.current.turns_taken"])
        end)

        it("serializes multiple chapters and current points to highest", function()
            local svc = new_service()
            svc:begin_chapter(1, "battle_1")
            svc:record_battle_end({ chapter = 1, turn_number = 3, result = "VICTORY" })
            svc:begin_chapter(2, "battle_2")
            svc:record_battle_end({ chapter = 2, turn_number = 7, result = "VICTORY" })
            local map = svc:get_as_map()
            luassert.are_equal("0", map["stats.1.units_lost"])
            luassert.are_equal("3", map["stats.1.turns_taken"])
            luassert.are_equal("0", map["stats.2.units_lost"])
            luassert.are_equal("7", map["stats.2.turns_taken"])
            luassert.are_equal("0", map["stats.current.units_lost"])
            luassert.are_equal("7", map["stats.current.turns_taken"])
        end)

        it("counts units_lost correctly", function()
            local svc = new_service()
            svc:begin_chapter(1, "battle_1")
            svc:record_death({ chapter = 1, defender = { id = 10 }, attacker = { id = 20 }, turn_number = 2 })
            svc:record_death({ chapter = 1, defender = { id = 11 }, attacker = { id = 20 }, turn_number = 3 })
            local map = svc:get_as_map()
            luassert.are_equal("2", map["stats.1.units_lost"])
            luassert.are_equal("2", map["stats.current.units_lost"])
        end)
    end)

    describe("record_combat", function()
        it("increments the attacker's combat count", function()
            local svc = new_service()
            svc:record_combat({ attacker_id = 1, defender_id = 2, chapter = 1 })
            luassert.are_equal(1, svc.story_results.unit_combats[1])
        end)

        it("increments the defender's combat count", function()
            local svc = new_service()
            svc:record_combat({ attacker_id = 1, defender_id = 2, chapter = 1 })
            luassert.are_equal(1, svc.story_results.unit_combats[2])
        end)

        it("accumulates across multiple combats", function()
            local svc = new_service()
            svc:record_combat({ attacker_id = 1, defender_id = 2, chapter = 1 })
            svc:record_combat({ attacker_id = 1, defender_id = 3, chapter = 1 })
            luassert.are_equal(2, svc.story_results.unit_combats[1])
            luassert.are_equal(1, svc.story_results.unit_combats[2])
            luassert.are_equal(1, svc.story_results.unit_combats[3])
        end)

        it("unit_combats starts empty", function()
            local svc = new_service()
            luassert.are_same({}, svc.story_results.unit_combats)
        end)
    end)
end)
