return {
    version = "1.10",
    luaversion = "5.1",
    tiledversion = "1.12.1",
    class = "",
    orientation = "orthogonal",
    renderorder = "right-down",
    width = 20,
    height = 24,
    tilewidth = 16,
    tileheight = 16,
    nextlayerid = 20,
    nextobjectid = 66,
    properties = {},
    tilesets = {
        {
            name = "tiny_tileset",
            firstgid = 1,
            filename = "tiny_tileset.tsx"
        }
    },
    layers = {
        {
            type = "tilelayer",
            x = 0,
            y = 0,
            width = 20,
            height = 24,
            id = 1,
            name = "ground",
            class = "",
            visible = true,
            opacity = 1,
            offsetx = 0,
            offsety = 0,
            parallaxx = 1,
            parallaxy = 1,
            properties = {},
            encoding = "lua",
            data = {
                11, 11, 11, 11, 11, 11, 11, 11, 164, 162, 162, 165, 11, 11, 11, 11, 11, 11, 11, 11,
                11, 11, 11, 11, 11, 11, 11, 11, 180, 162, 162, 181, 180, 11, 11, 11, 11, 11, 11, 11,
                11, 162, 162, 162, 162, 162, 162, 162, 162, 162, 162, 162, 162, 162, 162, 162, 162, 162, 162, 11,
                11, 162, 162, 162, 162, 162, 162, 162, 162, 162, 162, 162, 162, 162, 162, 162, 162, 162, 162, 11,
                11, 162, 162, 162, 162, 162, 162, 162, 162, 162, 162, 162, 162, 162, 162, 162, 162, 162, 162, 11,
                11, 162, 162, 162, 162, 162, 162, 162, 162, 162, 162, 162, 162, 162, 162, 162, 162, 162, 162, 11,
                11, 200, 202, 11, 11, 200, 202, 11, 11, 11, 11, 11, 11, 200, 202, 148, 149, 149, 149, 11,
                11, 200, 202, 11, 11, 200, 202, 11, 11, 11, 11, 11, 11, 200, 202, 197, 204, 204, 204, 11,
                11, 200, 202, 11, 162, 162, 162, 162, 162, 162, 162, 162, 162, 162, 162, 162, 162, 162, 162, 11,
                11, 200, 202, 11, 162, 162, 162, 162, 162, 162, 162, 162, 162, 162, 162, 162, 162, 162, 162, 11,
                11, 200, 202, 11, 162, 162, 162, 162, 162, 162, 162, 162, 162, 162, 162, 162, 11, 162, 162, 11,
                11, 200, 202, 11, 11, 11, 11, 11, 200, 201, 201, 202, 11, 11, 11, 11, 11, 200, 202, 11,
                65, 17, 19, 65, 11, 11, 11, 11, 200, 201, 201, 202, 11, 11, 11, 11, 65, 21, 35, 65,
                65, 33, 35, 65, 11, 11, 11, 11, 200, 201, 201, 202, 11, 11, 11, 11, 65, 36, 65, 65,
                65, 4, 66, 65, 65, 66, 65, 65, 17, 18, 18, 19, 65, 65, 65, 65, 65, 4, 65, 65,
                65, 36, 65, 65, 66, 67, 66, 65, 33, 18, 18, 19, 65, 65, 65, 65, 65, 37, 3, 65,
                65, 1, 3, 65, 65, 65, 65, 65, 65, 17, 18, 19, 65, 65, 65, 65, 65, 17, 19, 65,
                65, 17, 19, 65, 65, 65, 65, 65, 1, 18, 18, 19, 66, 49, 51, 66, 1, 18, 38, 2,
                3, 33, 10, 3, 65, 65, 65, 65, 33, 23, 18, 18, 51, 66, 66, 49, 55, 34, 34, 34,
                35, 1, 39, 19, 65, 65, 65, 65, 65, 17, 22, 35, 65, 65, 65, 65, 65, 65, 65, 65,
                65, 33, 34, 54, 7, 2, 2, 2, 2, 39, 38, 3, 65, 65, 65, 65, 65, 65, 66, 65,
                65, 65, 66, 65, 33, 34, 34, 34, 23, 18, 22, 35, 65, 65, 65, 65, 67, 65, 65, 65,
                65, 65, 65, 65, 65, 65, 65, 66, 33, 23, 19, 65, 65, 65, 65, 65, 66, 66, 65, 65,
                65, 65, 65, 65, 65, 65, 65, 65, 65, 17, 38, 3, 66, 65, 66, 65, 65, 65, 65, 65
            }
        },
        {
            type = "tilelayer",
            x = 0,
            y = 0,
            width = 20,
            height = 24,
            id = 7,
            name = "decoration_1",
            class = "",
            visible = true,
            opacity = 1,
            offsetx = 0,
            offsety = 0,
            parallaxx = 1,
            parallaxy = 1,
            properties = {},
            encoding = "lua",
            data = {
                204, 204, 204, 204, 164, 0, 0, 165, 204, 204, 204, 204, 164, 0, 0, 165, 204, 204, 204, 204,
                204, 204, 204, 204, 180, 0, 0, 181, 204, 204, 204, 204, 180, 0, 0, 181, 204, 204, 204, 204,
                199, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 197,
                199, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 197,
                199, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 197,
                199, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 197,
                150, 0, 0, 148, 150, 0, 0, 148, 149, 149, 149, 149, 150, 0, 0, 0, 0, 0, 0, 149,
                199, 0, 0, 197, 199, 0, 0, 197, 204, 204, 204, 204, 199, 0, 0, 0, 0, 0, 0, 204,
                199, 0, 0, 198, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 197,
                199, 0, 0, 198, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 197,
                199, 0, 0, 198, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 151, 0, 0, 148,
                199, 0, 0, 198, 148, 149, 149, 150, 0, 0, 0, 0, 148, 149, 149, 150, 198, 0, 0, 197,
                0, 0, 0, 0, 197, 204, 204, 199, 0, 0, 0, 0, 197, 204, 204, 199, 0, 0, 0, 0,
                0, 0, 0, 0, 197, 204, 204, 199, 0, 0, 0, 0, 197, 204, 204, 199, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
            }
        },
        {
            type = "objectgroup",
            draworder = "topdown",
            id = 8,
            name = "reinforce_north_east",
            class = "",
            visible = true,
            opacity = 1,
            offsetx = 0,
            offsety = 0,
            parallaxx = 1,
            parallaxy = 1,
            properties = {
                ["from"] = "north"
            },
            objects = {
                {
                    id = 26,
                    name = "",
                    type = "",
                    shape = "point",
                    x = 208,
                    y = 16,
                    width = 0,
                    height = 0,
                    rotation = 0,
                    opacity = 1,
                    visible = true,
                    properties = {}
                },
                {
                    id = 27,
                    name = "",
                    type = "",
                    shape = "point",
                    x = 224,
                    y = 16,
                    width = 0,
                    height = 0,
                    rotation = 0,
                    opacity = 1,
                    visible = true,
                    properties = {}
                }
            }
        },
        {
            type = "objectgroup",
            draworder = "topdown",
            id = 9,
            name = "reinforce_north_west",
            class = "",
            visible = true,
            opacity = 1,
            offsetx = 0,
            offsety = 0,
            parallaxx = 1,
            parallaxy = 1,
            properties = {
                ["from"] = "north"
            },
            objects = {
                {
                    id = 24,
                    name = "",
                    type = "",
                    shape = "point",
                    x = 80,
                    y = 16,
                    width = 0,
                    height = 0,
                    rotation = 0,
                    opacity = 1,
                    visible = true,
                    properties = {}
                },
                {
                    id = 25,
                    name = "",
                    type = "",
                    shape = "point",
                    x = 96,
                    y = 16,
                    width = 0,
                    height = 0,
                    rotation = 0,
                    opacity = 1,
                    visible = true,
                    properties = {}
                }
            }
        },
        {
            type = "objectgroup",
            draworder = "topdown",
            id = 3,
            name = "deployment_defense",
            class = "",
            visible = true,
            opacity = 1,
            offsetx = 0,
            offsety = 0,
            parallaxx = 1,
            parallaxy = 1,
            properties = {},
            objects = {
                {
                    id = 4,
                    name = "",
                    type = "",
                    shape = "point",
                    x = 144,
                    y = 32,
                    width = 0,
                    height = 0,
                    rotation = 0,
                    opacity = 1,
                    visible = true,
                    properties = {}
                },
                {
                    id = 5,
                    name = "",
                    type = "",
                    shape = "point",
                    x = 176,
                    y = 32,
                    width = 0,
                    height = 0,
                    rotation = 0,
                    opacity = 1,
                    visible = true,
                    properties = {}
                },
                {
                    id = 6,
                    name = "",
                    type = "",
                    shape = "point",
                    x = 112,
                    y = 32,
                    width = 0,
                    height = 0,
                    rotation = 0,
                    opacity = 1,
                    visible = true,
                    properties = {}
                },
                {
                    id = 7,
                    name = "",
                    type = "",
                    shape = "point",
                    x = 128,
                    y = 48,
                    width = 0,
                    height = 0,
                    rotation = 0,
                    opacity = 1,
                    visible = true,
                    properties = {}
                },
                {
                    id = 8,
                    name = "",
                    type = "",
                    shape = "point",
                    x = 160,
                    y = 48,
                    width = 0,
                    height = 0,
                    rotation = 0,
                    opacity = 1,
                    visible = true,
                    properties = {}
                },
                {
                    id = 9,
                    name = "",
                    type = "",
                    shape = "point",
                    x = 192,
                    y = 48,
                    width = 0,
                    height = 0,
                    rotation = 0,
                    opacity = 1,
                    visible = true,
                    properties = {}
                },
                {
                    id = 10,
                    name = "",
                    type = "",
                    shape = "point",
                    x = 208,
                    y = 32,
                    width = 0,
                    height = 0,
                    rotation = 0,
                    opacity = 1,
                    visible = true,
                    properties = {}
                },
                {
                    id = 12,
                    name = "",
                    type = "",
                    shape = "point",
                    x = 96,
                    y = 48,
                    width = 0,
                    height = 0,
                    rotation = 0,
                    opacity = 1,
                    visible = true,
                    properties = {}
                }
            }
        },
        {
            type = "objectgroup",
            draworder = "topdown",
            id = 4,
            name = "deployment_seize",
            class = "",
            visible = true,
            opacity = 1,
            offsetx = 0,
            offsety = 0,
            parallaxx = 1,
            parallaxy = 1,
            properties = {},
            objects = {
                {
                    id = 13,
                    name = "",
                    type = "",
                    shape = "point",
                    x = 128,
                    y = 368,
                    width = 0,
                    height = 0,
                    rotation = 0,
                    opacity = 1,
                    visible = true,
                    properties = {}
                },
                {
                    id = 14,
                    name = "",
                    type = "",
                    shape = "point",
                    x = 160,
                    y = 368,
                    width = 0,
                    height = 0,
                    rotation = 0,
                    opacity = 1,
                    visible = true,
                    properties = {}
                },
                {
                    id = 15,
                    name = "",
                    type = "",
                    shape = "point",
                    x = 192,
                    y = 368,
                    width = 0,
                    height = 0,
                    rotation = 0,
                    opacity = 1,
                    visible = true,
                    properties = {}
                },
                {
                    id = 16,
                    name = "",
                    type = "",
                    shape = "point",
                    x = 112,
                    y = 352,
                    width = 0,
                    height = 0,
                    rotation = 0,
                    opacity = 1,
                    visible = true,
                    properties = {}
                },
                {
                    id = 17,
                    name = "",
                    type = "",
                    shape = "point",
                    x = 144,
                    y = 352,
                    width = 0,
                    height = 0,
                    rotation = 0,
                    opacity = 1,
                    visible = true,
                    properties = {}
                },
                {
                    id = 18,
                    name = "",
                    type = "",
                    shape = "point",
                    x = 176,
                    y = 352,
                    width = 0,
                    height = 0,
                    rotation = 0,
                    opacity = 1,
                    visible = true,
                    properties = {}
                },
                {
                    id = 19,
                    name = "",
                    type = "",
                    shape = "point",
                    x = 128,
                    y = 336,
                    width = 0,
                    height = 0,
                    rotation = 0,
                    opacity = 1,
                    visible = true,
                    properties = {}
                },
                {
                    id = 20,
                    name = "",
                    type = "",
                    shape = "point",
                    x = 160,
                    y = 336,
                    width = 0,
                    height = 0,
                    rotation = 0,
                    opacity = 1,
                    visible = true,
                    properties = {}
                }
            }
        },
        {
            type = "objectgroup",
            draworder = "topdown",
            id = 5,
            name = "boss_seize",
            class = "",
            visible = true,
            opacity = 1,
            offsetx = 0,
            offsety = 0,
            parallaxx = 1,
            parallaxy = 1,
            properties = {
                ["ai_hint"] = "stationary",
                ["slot"] = "enemy_commander"
            },
            objects = {
                {
                    id = 21,
                    name = "",
                    type = "",
                    shape = "point",
                    x = 160,
                    y = 32,
                    width = 0,
                    height = 0,
                    rotation = 0,
                    opacity = 1,
                    visible = true,
                    properties = {}
                }
            }
        },
        {
            type = "objectgroup",
            draworder = "topdown",
            id = 6,
            name = "reinforce_west",
            class = "",
            visible = true,
            opacity = 1,
            offsetx = 0,
            offsety = 0,
            parallaxx = 1,
            parallaxy = 1,
            properties = {
                ["from"] = "west"
            },
            objects = {
                {
                    id = 22,
                    name = "",
                    type = "",
                    shape = "point",
                    x = 0,
                    y = 288,
                    width = 0,
                    height = 0,
                    rotation = 0,
                    opacity = 1,
                    visible = true,
                    properties = {}
                },
                {
                    id = 23,
                    name = "",
                    type = "",
                    shape = "point",
                    x = 0,
                    y = 304,
                    width = 0,
                    height = 0,
                    rotation = 0,
                    opacity = 1,
                    visible = true,
                    properties = {}
                }
            }
        },
        {
            type = "objectgroup",
            draworder = "topdown",
            id = 10,
            name = "reinforce_east",
            class = "",
            visible = true,
            opacity = 1,
            offsetx = 0,
            offsety = 0,
            parallaxx = 1,
            parallaxy = 1,
            properties = {
                ["from"] = "east"
            },
            objects = {
                {
                    id = 28,
                    name = "",
                    type = "",
                    shape = "point",
                    x = 304,
                    y = 272,
                    width = 0,
                    height = 0,
                    rotation = 0,
                    opacity = 1,
                    visible = true,
                    properties = {}
                },
                {
                    id = 29,
                    name = "",
                    type = "",
                    shape = "point",
                    x = 304,
                    y = 288,
                    width = 0,
                    height = 0,
                    rotation = 0,
                    opacity = 1,
                    visible = true,
                    properties = {}
                }
            }
        },
        {
            type = "tilelayer",
            x = 0,
            y = 0,
            width = 20,
            height = 24,
            id = 2,
            name = "front_walls",
            class = "",
            visible = true,
            opacity = 1,
            offsetx = 0,
            offsety = 0,
            parallaxx = 1,
            parallaxy = 1,
            properties = {},
            encoding = "lua",
            data = {
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                79, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 77,
                79, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 62, 62, 62, 62, 0, 0, 0, 77,
                79, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 61, 78, 78, 78, 95, 0, 0, 0, 77,
                79, 0, 0, 0, 0, 62, 0, 0, 0, 0, 0, 93, 78, 78, 78, 63, 62, 0, 0, 77,
                79, 0, 0, 0, 61, 78, 63, 0, 0, 0, 0, 0, 93, 78, 78, 78, 95, 0, 0, 77,
                79, 0, 0, 77, 78, 78, 78, 79, 0, 0, 0, 0, 0, 94, 94, 94, 0, 0, 0, 0,
                0, 0, 0, 77, 78, 78, 78, 79, 0, 0, 0, 0, 0, 62, 62, 62, 62, 62, 0, 0,
                0, 0, 0, 0, 94, 94, 94, 0, 0, 0, 0, 0, 77, 78, 78, 78, 78, 78, 79, 77,
                62, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 77, 78, 78, 78, 95, 94, 0, 77,
                78, 63, 62, 62, 62, 0, 0, 0, 0, 0, 0, 0, 77, 78, 95, 94, 0, 0, 0, 77,
                78, 78, 78, 78, 78, 63, 62, 0, 0, 0, 0, 0, 0, 94, 0, 0, 0, 0, 62, 61,
                78, 78, 78, 78, 78, 78, 78, 63, 0, 0, 0, 0, 0, 0, 0, 62, 62, 61, 78, 78
            }
        },
        {
            type = "objectgroup",
            draworder = "topdown",
            id = 12,
            name = "guard_west",
            class = "",
            visible = true,
            opacity = 1,
            offsetx = 0,
            offsety = 0,
            parallaxx = 1,
            parallaxy = 1,
            properties = {},
            objects = {
                {
                    id = 30,
                    name = "",
                    type = "",
                    shape = "point",
                    x = 16,
                    y = 192,
                    width = 0,
                    height = 0,
                    rotation = 0,
                    opacity = 1,
                    visible = true,
                    properties = {}
                },
                {
                    id = 31,
                    name = "",
                    type = "",
                    shape = "point",
                    x = 32,
                    y = 192,
                    width = 0,
                    height = 0,
                    rotation = 0,
                    opacity = 1,
                    visible = true,
                    properties = {}
                }
            }
        },
        {
            type = "objectgroup",
            draworder = "topdown",
            id = 13,
            name = "guard_east",
            class = "",
            visible = true,
            opacity = 1,
            offsetx = 0,
            offsety = 0,
            parallaxx = 1,
            parallaxy = 1,
            properties = {},
            objects = {
                {
                    id = 32,
                    name = "",
                    type = "",
                    shape = "point",
                    x = 288,
                    y = 192,
                    width = 0,
                    height = 0,
                    rotation = 0,
                    opacity = 1,
                    visible = true,
                    properties = {}
                },
                {
                    id = 33,
                    name = "",
                    type = "",
                    shape = "point",
                    x = 272,
                    y = 192,
                    width = 0,
                    height = 0,
                    rotation = 0,
                    opacity = 1,
                    visible = true,
                    properties = {}
                }
            }
        },
        {
            type = "objectgroup",
            draworder = "topdown",
            id = 14,
            name = "squad_center",
            class = "",
            visible = true,
            opacity = 1,
            offsetx = 0,
            offsety = 0,
            parallaxx = 1,
            parallaxy = 1,
            properties = {},
            objects = {
                {
                    id = 34,
                    name = "",
                    type = "",
                    shape = "point",
                    x = 80,
                    y = 144,
                    width = 0,
                    height = 0,
                    rotation = 0,
                    opacity = 1,
                    visible = true,
                    properties = {}
                },
                {
                    id = 35,
                    name = "",
                    type = "",
                    shape = "point",
                    x = 96,
                    y = 144,
                    width = 0,
                    height = 0,
                    rotation = 0,
                    opacity = 1,
                    visible = true,
                    properties = {}
                },
                {
                    id = 36,
                    name = "",
                    type = "",
                    shape = "point",
                    x = 224,
                    y = 144,
                    width = 0,
                    height = 0,
                    rotation = 0,
                    opacity = 1,
                    visible = true,
                    properties = {}
                },
                {
                    id = 37,
                    name = "",
                    type = "",
                    shape = "point",
                    x = 208,
                    y = 144,
                    width = 0,
                    height = 0,
                    rotation = 0,
                    opacity = 1,
                    visible = true,
                    properties = {}
                },
                {
                    id = 38,
                    name = "",
                    type = "",
                    shape = "point",
                    x = 144,
                    y = 144,
                    width = 0,
                    height = 0,
                    rotation = 0,
                    opacity = 1,
                    visible = true,
                    properties = {}
                },
                {
                    id = 39,
                    name = "",
                    type = "",
                    shape = "point",
                    x = 160,
                    y = 144,
                    width = 0,
                    height = 0,
                    rotation = 0,
                    opacity = 1,
                    visible = true,
                    properties = {}
                }
            }
        },
        {
            type = "objectgroup",
            draworder = "topdown",
            id = 15,
            name = "squad_north",
            class = "",
            visible = true,
            opacity = 1,
            offsetx = 0,
            offsety = 0,
            parallaxx = 1,
            parallaxy = 1,
            properties = {},
            objects = {
                {
                    id = 43,
                    name = "",
                    type = "",
                    shape = "point",
                    x = 16,
                    y = 80,
                    width = 0,
                    height = 0,
                    rotation = 0,
                    opacity = 1,
                    visible = true,
                    properties = {}
                },
                {
                    id = 44,
                    name = "",
                    type = "",
                    shape = "point",
                    x = 32,
                    y = 80,
                    width = 0,
                    height = 0,
                    rotation = 0,
                    opacity = 1,
                    visible = true,
                    properties = {}
                },
                {
                    id = 45,
                    name = "",
                    type = "",
                    shape = "point",
                    x = 144,
                    y = 80,
                    width = 0,
                    height = 0,
                    rotation = 0,
                    opacity = 1,
                    visible = true,
                    properties = {}
                },
                {
                    id = 46,
                    name = "",
                    type = "",
                    shape = "point",
                    x = 160,
                    y = 80,
                    width = 0,
                    height = 0,
                    rotation = 0,
                    opacity = 1,
                    visible = true,
                    properties = {}
                }
            }
        },
        {
            type = "objectgroup",
            draworder = "topdown",
            id = 16,
            name = "squad_east",
            class = "",
            visible = true,
            opacity = 1,
            offsetx = 0,
            offsety = 0,
            parallaxx = 1,
            parallaxy = 1,
            properties = {},
            objects = {
                {
                    id = 51,
                    name = "",
                    type = "",
                    shape = "point",
                    x = 272,
                    y = 224,
                    width = 0,
                    height = 0,
                    rotation = 0,
                    opacity = 1,
                    visible = true,
                    properties = {}
                },
                {
                    id = 52,
                    name = "",
                    type = "",
                    shape = "point",
                    x = 288,
                    y = 224,
                    width = 0,
                    height = 0,
                    rotation = 0,
                    opacity = 1,
                    visible = true,
                    properties = {}
                },
                {
                    id = 53,
                    name = "",
                    type = "",
                    shape = "point",
                    x = 272,
                    y = 256,
                    width = 0,
                    height = 0,
                    rotation = 0,
                    opacity = 1,
                    visible = true,
                    properties = {}
                },
                {
                    id = 54,
                    name = "",
                    type = "",
                    shape = "point",
                    x = 288,
                    y = 256,
                    width = 0,
                    height = 0,
                    rotation = 0,
                    opacity = 1,
                    visible = true,
                    properties = {}
                }
            }
        },
        {
            type = "objectgroup",
            draworder = "topdown",
            id = 17,
            name = "squad_west",
            class = "",
            visible = true,
            opacity = 1,
            offsetx = 0,
            offsety = 0,
            parallaxx = 1,
            parallaxy = 1,
            properties = {},
            objects = {
                {
                    id = 55,
                    name = "",
                    type = "",
                    shape = "point",
                    x = 32,
                    y = 320,
                    width = 0,
                    height = 0,
                    rotation = 0,
                    opacity = 1,
                    visible = true,
                    properties = {}
                },
                {
                    id = 56,
                    name = "",
                    type = "",
                    shape = "point",
                    x = 48,
                    y = 304,
                    width = 0,
                    height = 0,
                    rotation = 0,
                    opacity = 1,
                    visible = true,
                    properties = {}
                },
                {
                    id = 57,
                    name = "",
                    type = "",
                    shape = "point",
                    x = 32,
                    y = 288,
                    width = 0,
                    height = 0,
                    rotation = 0,
                    opacity = 1,
                    visible = true,
                    properties = {}
                },
                {
                    id = 58,
                    name = "",
                    type = "",
                    shape = "point",
                    x = 16,
                    y = 304,
                    width = 0,
                    height = 0,
                    rotation = 0,
                    opacity = 1,
                    visible = true,
                    properties = {}
                }
            }
        },
        {
            type = "objectgroup",
            draworder = "topdown",
            id = 18,
            name = "squad_center_south",
            class = "",
            visible = true,
            opacity = 1,
            offsetx = 0,
            offsety = 0,
            parallaxx = 1,
            parallaxy = 1,
            properties = {},
            objects = {
                {
                    id = 59,
                    name = "",
                    type = "",
                    shape = "point",
                    x = 144,
                    y = 224,
                    width = 0,
                    height = 0,
                    rotation = 0,
                    opacity = 1,
                    visible = true,
                    properties = {}
                },
                {
                    id = 60,
                    name = "",
                    type = "",
                    shape = "point",
                    x = 160,
                    y = 224,
                    width = 0,
                    height = 0,
                    rotation = 0,
                    opacity = 1,
                    visible = true,
                    properties = {}
                }
            }
        },
        {
            type = "objectgroup",
            draworder = "topdown",
            id = 19,
            name = "reinforce_south",
            class = "",
            visible = true,
            opacity = 1,
            offsetx = 0,
            offsety = 0,
            parallaxx = 1,
            parallaxy = 1,
            properties = {
                ["from"] = "south"
            },
            objects = {
                {
                    id = 62,
                    name = "",
                    type = "",
                    shape = "point",
                    x = 128,
                    y = 368,
                    width = 0,
                    height = 0,
                    rotation = 0,
                    opacity = 1,
                    visible = true,
                    properties = {}
                },
                {
                    id = 63,
                    name = "",
                    type = "",
                    shape = "point",
                    x = 144,
                    y = 368,
                    width = 0,
                    height = 0,
                    rotation = 0,
                    opacity = 1,
                    visible = true,
                    properties = {}
                },
                {
                    id = 64,
                    name = "",
                    type = "",
                    shape = "point",
                    x = 160,
                    y = 368,
                    width = 0,
                    height = 0,
                    rotation = 0,
                    opacity = 1,
                    visible = true,
                    properties = {}
                },
                {
                    id = 65,
                    name = "",
                    type = "",
                    shape = "point",
                    x = 176,
                    y = 368,
                    width = 0,
                    height = 0,
                    rotation = 0,
                    opacity = 1,
                    visible = true,
                    properties = {}
                }
            }
        }
    }
}
