local luassert = require("luassert")
local spy = require("luassert.spy")
local save_system = require("src.tactics.save.save_system")

describe("save_system", function()
    describe("delete", function()
        it("should call rm with the correct path", function()
            local rm_spy = spy.on(_G, "rm")
            save_system.delete("my_save")
            luassert.spy(rm_spy).was_called_with("/appdata/tactics_tales/saves/my_save.pod")
            rm_spy:revert()
        end)
    end)
end)
