local luassert = require("luassert")
local spy = require("luassert.spy")
local save_system = require("src.tactics.save.save_system")

describe("save_system", function()
    describe("delete", function()
        local rm_spy
        before_each(function()
            rm_spy = spy.on(_G, "rm")
        end)
        after_each(function()
            rm_spy:revert()
        end)
        it("should call rm with the correct path", function()
            save_system.delete("my_save")
            ---@diagnostic disable-next-line: undefined-field
            luassert.spy(rm_spy).was_called_with("/appdata/tactics_tales/saves/my_save.pod")
        end)
    end)
end)
