local luassert = require("luassert")
local campaign_harness = require("src.integration.helpers.campaign_harness")

describe("story battle flow #it", function()
    local h

    after_each(function()
        if h then h:teardown() end
    end)

    describe("permadeath", function()
        it("emits TACTICS_UNIT_DEATH when player unit dies", function()
            h = campaign_harness.new()
            h:start_campaign("close_combat", { permadeath = false })
            h:finish_player_turn()
            luassert.are_equal(1, #h:emitted("TACTICS_UNIT_DEATH"))
        end)

        it("permadeath=false: player character remains in roster after dying", function()
            h = campaign_harness.new()
            h:start_campaign("close_combat", { permadeath = false })
            h:finish_player_turn()
            luassert.are_equal(1, #h:player_roster())
        end)

        it("permadeath=true: player character removed from roster after dying", function()
            h = campaign_harness.new()
            h:start_campaign("close_combat", { permadeath = true })
            h:finish_player_turn()
            luassert.are_equal(0, #h:player_roster())
        end)
    end)

    describe("battle_and_exit story", function()
        it("story is not complete before finish_player_turn", function()
            h = campaign_harness.new()
            h:start_campaign("battle_and_exit")
            luassert.is_false(h:is_complete())
        end)

        it("story is complete after finish_player_turn (victory path)", function()
            h = campaign_harness.new()
            h:start_campaign("battle_and_exit")
            h:finish_player_turn()
            luassert.is_true(h:is_complete())
        end)

        it("emits GAME_EXIT_CAMPAIGN after battle victory", function()
            h = campaign_harness.new()
            h:start_campaign("battle_and_exit")
            h:finish_player_turn()
            luassert.are_equal(1, #h:emitted("GAME_EXIT_CAMPAIGN"))
        end)
    end)
end)
