local luassert = require("luassert")
local battle_harness = require("src.integration.helpers.battle_harness")

describe("battle flow #it", function()
    describe("events", function()
        it("emits TACTICS_BEGIN_BATTLE on start", function()
            local h = battle_harness.new()
            h:start_battle("rout_no_enemies")
            luassert.are_equal(1, #h:emitted("TACTICS_BEGIN_BATTLE"))
            h:teardown()
        end)

        it("emits TACTICS_BEGIN_TURN with turn=1 on start", function()
            local h = battle_harness.new()
            h:start_battle("rout_no_enemies")
            local turns = h:emitted("TACTICS_BEGIN_TURN")
            luassert.are_equal(1, #turns)
            luassert.are_equal(1, turns[1].turn)
            h:teardown()
        end)
    end)

    describe("rout_no_enemies", function()
        it("battle_result is VICTORY after finish_player_turn", function()
            local h = battle_harness.new()
            h:start_battle("rout_no_enemies")
            h:finish_player_turn()
            luassert.are_equal("VICTORY", h:battle_result())
            h:teardown()
        end)

        it("emits BATTLE_END once", function()
            local h = battle_harness.new()
            h:start_battle("rout_no_enemies")
            h:finish_player_turn()
            luassert.are_equal(1, #h:emitted("BATTLE_END"))
            h:teardown()
        end)

        it("BATTLE_END payload has result='VICTORY'", function()
            local h = battle_harness.new()
            h:start_battle("rout_no_enemies")
            h:finish_player_turn()
            luassert.are_equal("VICTORY", h:emitted("BATTLE_END")[1].result)
            h:teardown()
        end)
    end)

    describe("turn_limit_defeat", function()
        it("battle not over after one finish_player_turn", function()
            local h = battle_harness.new()
            h:start_battle("turn_limit_defeat")
            h:finish_player_turn()
            luassert.is_nil(h:battle_result())
            h:teardown()
        end)

        it("battle_result is DEFEAT after two finish_player_turns", function()
            local h = battle_harness.new()
            h:start_battle("turn_limit_defeat")
            h:finish_player_turn()
            h:finish_player_turn()
            luassert.are_equal("DEFEAT", h:battle_result())
            h:teardown()
        end)

        it("BATTLE_END payload has result='DEFEAT'", function()
            local h = battle_harness.new()
            h:start_battle("turn_limit_defeat")
            h:finish_player_turn()
            h:finish_player_turn()
            luassert.are_equal("DEFEAT", h:emitted("BATTLE_END")[1].result)
            h:teardown()
        end)

        it("emits TACTICS_BEGIN_TURN twice (turns 1 and 2) before defeat", function()
            local h = battle_harness.new()
            h:start_battle("turn_limit_defeat")
            h:finish_player_turn()
            h:finish_player_turn()
            local turns = h:emitted("TACTICS_BEGIN_TURN")
            luassert.are_equal(2, #turns)
            luassert.are_equal(1, turns[1].turn)
            luassert.are_equal(2, turns[2].turn)
            h:teardown()
        end)
    end)
end)
