local luassert = require("luassert")

local event_bus = require("src.tactics.systems.event_bus")

describe("tactics.systems.event_bus", function()
    describe("on", function()
        it("should return a unique ID per subscription", function()
            local bus = event_bus.new()
            local id1 = bus:on("TACTICS_BEGIN_TURN", function() end)
            local id2 = bus:on("TACTICS_BEGIN_TURN", function() end)
            luassert.are_not_equal(id1, id2)
        end)
    end)

    describe("emit", function()
        it("should call the registered callback", function()
            local bus = event_bus.new()
            local called = false
            bus:on("TACTICS_BEGIN_TURN", function() called = true end)
            bus:emit("TACTICS_BEGIN_TURN", {})
            luassert.is_true(called)
        end)

        it("should pass args to the callback", function()
            local bus = event_bus.new()
            ---@class DummyMessage
            ---@field turn integer
            local received = nil
            bus:on("TACTICS_BEGIN_TURN", function(args) received = args end)
            bus:emit("TACTICS_BEGIN_TURN", { turn = 3 })
            luassert.are_equal(3, received.turn)
        end)

        it("should not call callbacks registered for other events", function()
            local bus = event_bus.new()
            local called = false
            bus:on("TACTICS_BEGIN_TURN", function() called = true end)
            bus:emit("TACTICS_END_TURN", {})
            luassert.is_false(called)
        end)

        it("should call all callbacks registered for the same event", function()
            local bus = event_bus.new()
            local count = 0
            bus:on("BATTLE_END_VICTORY", function() count = count + 1 end)
            bus:on("BATTLE_END_VICTORY", function() count = count + 1 end)
            bus:emit("BATTLE_END_VICTORY", {})
            luassert.are_equal(2, count)
        end)

        it("should record emitted events in history", function()
            local bus = event_bus.new()
            bus:emit("TACTICS_BEGIN_TURN", {})
            bus:emit("TACTICS_END_TURN", {})
            local history = bus:get_event_history(2)
            luassert.are_equal("TACTICS_BEGIN_TURN", history[1])
            luassert.are_equal("TACTICS_END_TURN", history[2])
        end)
    end)

    describe("remove", function()
        it("should stop invoking the callback after removal", function()
            local bus = event_bus.new()
            local called = false
            local id = bus:on("TACTICS_BEGIN_TURN", function() called = true end)
            bus:remove(id)
            bus:emit("TACTICS_BEGIN_TURN", {})
            luassert.is_false(called)
        end)

        it("should not affect other subscriptions on the same event", function()
            local bus = event_bus.new()
            local count = 0
            local id1 = bus:on("TACTICS_BEGIN_TURN", function() count = count + 1 end)
            bus:on("TACTICS_BEGIN_TURN", function() count = count + 1 end)
            bus:remove(id1)
            bus:emit("TACTICS_BEGIN_TURN", {})
            luassert.are_equal(1, count)
        end)

        it("should error when removing a non-existent ID", function()
            local bus = event_bus.new()
            luassert.has_error(function() bus:remove(999) end)
        end)
    end)

    describe("remove_all", function()
        it("should remove all provided subscription IDs", function()
            local bus = event_bus.new()
            local count = 0
            local id1 = bus:on("TACTICS_BEGIN_TURN", function() count = count + 1 end)
            local id2 = bus:on("TACTICS_END_TURN",   function() count = count + 1 end)
            bus:remove_all({ [id1] = true, [id2] = true })
            bus:emit("TACTICS_BEGIN_TURN", {})
            bus:emit("TACTICS_END_TURN", {})
            luassert.are_equal(0, count)
        end)
    end)

    describe("get_event_history", function()
        it("should return events in emission order up to row_limit", function()
            local bus = event_bus.new()
            bus:emit("TACTICS_BEGIN_TURN", {})
            bus:emit("TACTICS_END_TURN", {})
            bus:emit("BATTLE_END_VICTORY", {})
            local history = bus:get_event_history(2)
            luassert.are_equal("TACTICS_BEGIN_TURN", history[1])
            luassert.are_equal("TACTICS_END_TURN", history[2])
        end)
    end)
end)
