local luassert       = require("luassert")

local event_bus      = require("src.tactics.systems.event_bus")
local event_listener = require("src.tactics.systems.event_bus.event_listener")

describe("tactics.systems.event_bus.event_listener", function()
    describe("on", function()
        it("should subscribe the callback and return an ID", function()
            local bus = event_bus.new()
            local listener = event_listener.new(bus)
            local called = false
            local id = listener:on("TACTICS_BEGIN_TURN", function() called = true end)
            luassert.is_number(id)
            bus:emit("TACTICS_BEGIN_TURN", {})
            luassert.is_true(called)
        end)
    end)

    describe("remove", function()
        it("should unsubscribe the specified listener", function()
            local bus = event_bus.new()
            local listener = event_listener.new(bus)
            local called = false
            local id = listener:on("TACTICS_BEGIN_TURN", function() called = true end)
            listener:remove(id)
            bus:emit("TACTICS_BEGIN_TURN", {})
            luassert.is_false(called)
        end)

        it("should not affect other listeners managed by the same EventListener", function()
            local bus = event_bus.new()
            local listener = event_listener.new(bus)
            local count = 0
            local id1 = listener:on("TACTICS_BEGIN_TURN", function() count = count + 1 end)
            listener:on("TACTICS_BEGIN_TURN", function() count = count + 1 end)
            listener:remove(id1)
            bus:emit("TACTICS_BEGIN_TURN", {})
            luassert.are_equal(1, count)
        end)
    end)

    describe("teardown", function()
        it("should remove all managed subscriptions", function()
            local bus = event_bus.new()
            local listener = event_listener.new(bus)
            local count = 0
            listener:on("TACTICS_BEGIN_TURN", function() count = count + 1 end)
            listener:on("TACTICS_END_TURN", function() count = count + 1 end)
            listener:teardown()
            bus:emit("TACTICS_BEGIN_TURN", {})
            bus:emit("TACTICS_END_TURN", {})
            luassert.are_equal(0, count)
        end)

        it("should not affect subscriptions managed by a different EventListener", function()
            local bus = event_bus.new()
            local listener1 = event_listener.new(bus)
            local listener2 = event_listener.new(bus)
            local count = 0
            listener1:on("TACTICS_BEGIN_TURN", function() count = count + 1 end)
            listener2:on("TACTICS_BEGIN_TURN", function() count = count + 1 end)
            listener1:teardown()
            bus:emit("TACTICS_BEGIN_TURN", {})
            luassert.are_equal(1, count)
        end)
    end)
end)
