local luassert = require("luassert")

local mutex = require("src.tactics.systems.mutex")

describe("tactics.systems.mutex", function()
    describe("acquire", function()
        it("returns unique IDs on each call", function()
            local m = mutex.new()
            local a = m:acquire()
            local b = m:acquire()
            luassert.are_not_equal(a, b)
        end)
    end)

    describe("is_locked", function()
        it("is false when no locks are held", function()
            local m = mutex.new()
            luassert.is_false(m:is_locked())
        end)

        it("is true while a lock is held", function()
            local m = mutex.new()
            m:acquire()
            luassert.is_true(m:is_locked())
        end)

        it("is false after all locks are released", function()
            local m = mutex.new()
            local a = m:acquire()
            local b = m:acquire()
            m:release(a)
            luassert.is_true(m:is_locked())
            m:release(b)
            luassert.is_false(m:is_locked())
        end)
    end)

    describe("release", function()
        it("is a no-op for an unknown ID", function()
            local m = mutex.new()
            m:release(9999)
            luassert.is_false(m:is_locked())
        end)
    end)
end)
