--- @meta

--- [View Online](https://www.lexaloffle.com/dl/docs/picotron_manual.html#map)
--- @param tile_x integer
--- @param tile_y integer
--- @param sx? integer
--- @param sy? integer
--- @param tiles_x? integer
--- @param tiles_y? integer
--- @param p8layers? integer
--- @param tile_w? integer
--- @param tile_h? integer
-- global map: function(tile_x: any, tile_y: any, sx: any, sy: any, tiles_x: any, tiles_y: any, p8layers: any, tile_w: any, tile_h: any) 

--- [View Online](https://www.lexaloffle.com/dl/docs/picotron_manual.html#map)
--- @param src userdata
--- @param tile_x any
--- @param tile_y any
--- @param sx? any
--- @param sy? any
--- @param tiles_x? any
--- @param tiles_y? any
--- @param p8layers? any
--- @param tile_w? any
--- @param tile_h? any
global map: function(src: any, tile_x: any, tile_y: any, sx?: any, sy?: any, tiles_x?: any, tiles_y?: any, p8layers?: any, tile_w?: any, tile_h?: any) 

--- [View Online](https://www.lexaloffle.com/dl/docs/picotron_manual.html#mget)
--- @param x any
--- @param y any
global mget: function(x: any, y: any) 

--- [View Online](https://www.lexaloffle.com/dl/docs/picotron_manual.html#mset)
--- @param x any
--- @param y any
--- @param val any
global mset: function(x: any, y: any, val: any) 

--- [View Online](https://www.lexaloffle.com/dl/docs/picotron_manual.html#tline3d)
--- @param src_ud any
--- @param x0 any
--- @param y0 any
--- @param x1 any
--- @param y1 any
--- @param u0 any
--- @param v0 any
--- @param u1 any
--- @param v1 any
--- @param w0 any
--- @param w1 any
--- @param flags any
global tline3d: function(src_ud: any, x0: any, y0: any, x1: any, y1: any, u0: any, v0: any, u1: any, v1: any, w0: any, w1: any, flags: any) 
