---@brief
--- Expands parsed chunk records into the full set of transformation variants
--- permitted by each chunk's tags. See docs/specs/procgen-map-spec.md §4.6.

local TRANSFORM_TAGS = {
    rotate_90 = true, rotate_180 = true, flip_h = true, flip_v = true,
}

--- Canonical name suffix for a (n_rot, flipped) transformation pair.
---@param n integer 0-3 CW rotations
---@param f boolean whether flip_h is applied after rotations
---@return string
local function op_suffix(n, f)
    local rot_names = { [0] = "", [1] = "rot90", [2] = "rot180", [3] = "rot270" }
    -- Special aliases: (2,true) is flip_v; (0,true) is flip_h; others use "rotN|flip_h".
    if not f then
        return rot_names[n] == "" and "" or ("|" .. rot_names[n])
    elseif n == 0 then
        return "|flip_h"
    elseif n == 2 then
        return "|flip_v"
    else
        return "|" .. rot_names[n] .. "|flip_h"
    end
end

--- Compose two (n,f) transformations: apply op1 then op2.
---@param n1 integer
---@param f1 boolean
---@param n2 integer
---@param f2 boolean
---@return integer, boolean
local function compose(n1, f1, n2, f2)
    local sign = f1 and -1 or 1
    return (n1 + sign * n2) % 4, f1 ~= f2
end

--- Return the set of (n,f) group elements generated by the chunk's tags.
---@param tags string[]
---@return {[1]: integer, [2]: boolean}[]
local function generate_ops(tags)
    local has = {}
    for _, t in ipairs(tags) do has[t] = true end

    -- Collect generators as (n, f) pairs.
    local generators = {}
    if has["rotate_90"] then
        table.insert(generators, { 1, false })
    elseif has["rotate_180"] then
        table.insert(generators, { 2, false })
    end
    if has["flip_h"] then table.insert(generators, { 0, true }) end
    if has["flip_v"] then table.insert(generators, { 2, true }) end

    -- BFS closure starting from identity (0, false).
    local seen = {}
    local function key(n, f) return n * 2 + (f and 1 or 0) end
    local identity = { 0, false }
    seen[key(0, false)] = identity
    local queue = { identity }

    while #queue > 0 do
        local op = table.remove(queue, 1)
        for _, gen in ipairs(generators) do
            local cn, cf = compose(op[1], op[2], gen[1], gen[2])
            local k = key(cn, cf)
            if not seen[k] then
                local new_op = { cn, cf }
                seen[k] = new_op
                table.insert(queue, new_op)
            end
        end
    end

    local result = {}
    for _, op in pairs(seen) do
        table.insert(result, op)
    end
    return result
end

--- Apply a single 90° CW rotation to glyph rows.
---@param rows string[]
---@return string[]
local function rot90_rows(rows)
    local H = #rows
    local W = #rows[1]
    local new_rows = {}
    for r = 1, W do
        local chars = {}
        for c = 1, H do
            chars[c] = rows[H + 1 - c]:sub(r, r)
        end
        new_rows[r] = table.concat(chars)
    end
    return new_rows
end

--- Apply a horizontal flip (mirror left-right) to glyph rows.
---@param rows string[]
---@return string[]
local function flip_h_rows(rows)
    local result = {}
    for i, row in ipairs(rows) do
        result[i] = row:reverse()
    end
    return result
end

--- Reverse an exit zone range within a face of total length `face_len`.
---@param zone ExitZone?
---@param face_len integer
---@return ExitZone?
local function reverse_zone(zone, face_len)
    if not zone then return nil end
    return { min = face_len + 1 - zone.max, max = face_len + 1 - zone.min }
end

--- Remap exits for a single 90° CW rotation.
--- `total_h` is the row count BEFORE rotation.
---@param exits ChunkExits
---@param total_h integer
---@return ChunkExits
local function rot90_exits(exits, total_h)
    return {
        north = reverse_zone(exits.west, total_h),
        east  = exits.north,
        south = reverse_zone(exits.east, total_h),
        west  = exits.south,
    }
end

--- Remap exits for a horizontal flip.
---@param exits ChunkExits
---@param total_w integer
---@return ChunkExits
local function flip_h_exits(exits, total_w)
    return {
        north = reverse_zone(exits.north, total_w),
        south = reverse_zone(exits.south, total_w),
        east  = exits.west,
        west  = exits.east,
    }
end

--- Apply n 90° CW rotations, then flip_h if `f`, to rows and exits.
---@param rows string[]
---@param exits ChunkExits
---@param n integer
---@param f boolean
---@return string[], ChunkExits
local function apply_transform(rows, exits, n, f)
    for _ = 1, n do
        local h = #rows
        exits = rot90_exits(exits, h)
        rows  = rot90_rows(rows)
    end
    if f then
        local w = #rows[1]
        exits = flip_h_exits(exits, w)
        rows  = flip_h_rows(rows)
    end
    return rows, exits
end

--- Strip transformation tags from a tag list.
---@param tags string[]
---@return string[]
local function strip_transform_tags(tags)
    local result = {}
    for _, t in ipairs(tags) do
        if not TRANSFORM_TAGS[t] then
            table.insert(result, t)
        end
    end
    return result
end

--- Expand a list of base ChunkRecords into all permitted variants.
--- The original chunk is always included. Tile-identical variants are deduplicated.
---@param chunks ChunkRecord[]
---@return ChunkRecord[]
local function expand(chunks)
    local result = {}
    for _, chunk in ipairs(chunks) do
        local ops = generate_ops(chunk.tags)
        local seen_grids = {}

        for _, op in ipairs(ops) do
            local n, f = op[1], op[2]
            local new_rows, new_exits = apply_transform(chunk.rows, chunk.exits, n, f)
            local grid_key = table.concat(new_rows, "\n")

            if not seen_grids[grid_key] then
                seen_grids[grid_key] = true
                local suffix = op_suffix(n, f)
                local new_w = #new_rows[1] - 2
                local new_h = #new_rows - 2
                local variant = {
                    name   = chunk.name .. suffix,
                    width  = new_w,
                    height = new_h,
                    rows   = new_rows,
                    exits  = new_exits,
                    tags   = suffix == "" and chunk.tags or strip_transform_tags(chunk.tags),
                }
                table.insert(result, variant)
            end
        end
    end
    return result
end

local chunk_variants = { expand = expand }
return chunk_variants
